spring:
  application:
    name: ecommerce-platform
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:ecommercedb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  # JPA/Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Jackson properties
  jackson:
    serialization:
      fail-on-empty-beans: false

# Server configuration
server:
  port: 8080

# JWT configuration
app:
  jwt:
    secret: mySecretKey12345678901234567890123456789012
    expiration-ms: 86400000  # 24 hours

# Logging configuration
logging:
  level:
    root: INFO
    com.ecommerce: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationIdStrategy: METHOD
  packages-to-scan: com.ecommerce.controller
  paths-to-match: /api/** 