apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  labels:
    app: ecommerce
    tier: backend
spec:
  selector:
    app: ecommerce
    tier: backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-public
  labels:
    app: ecommerce
    tier: frontend
spec:
  selector:
    app: ecommerce
    tier: backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer 